version: 2

sources:
  - name: tulsi
    tables:
      - name: online_retail_ii
models:
  - name: bronzetable
    description: "Raw data loaded from DBFS."
  - name: silvertable
    description: "Cleaned and transformed data from the bronze table."
  - name: goldtable
    description: "Business-ready data for reporting and analytics."
